-- Database: test-boletia-db

DROP DATABASE IF EXISTS "test-boletia-db";

CREATE DATABASE "test-boletia-db"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE TABLE IF NOT EXISTS CURRENCIES (
    ID SERIAL PRIMARY KEY NOT NULL
    CODE TEXT NOT NULL,
    VALUE NUMERIC NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CALLS_LOG (
    ID SERIAL PRIMARY KEY NOT NULL,
    CALL_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RESPONSE_TIME_MS INT NOT NULL,
);

