-- Database: test-boletia-db

DROP DATABASE IF EXISTS "test-boletia-db";

CREATE DATABASE "test-boletia-db"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE TABLE CURRENCIES (
    ID SERIAL PRIMARY KEY,
    SYMBOL TEXT NOT NULL,
    NAME TEXT NOT NULL,
    SYMBOL_NATIVE TEXT NOT NULL,
    DECIMAL_DIGITS INT NOT NULL,
    ROUNDING INT NOT NULL,
    CODE TEXT NOT NULL,
    NAME_PLURAL TEXT NOT NULL
);

CREATE TABLE CALLS_LOG (
    ID SERIAL PRIMARY KEY,
    CURRENCY_ID INT NOT NULL,
    CALL_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RESPONSE_TIME_MS INT NOT NULL,
    FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCIES (ID)
);

